version: '3.8'
services:
  postgres-library:
    image: postgres:latest
    container_name: postgres-library
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: library
    ports:
      - "5432:5432"